x-env: &env
  MYSQL_ROOT_PASSWORD: deeltask123
  MYSQL_USER: deeltask
  MYSQL_PASSWORD: deeltask
  MYSQL_DATABASE: deel_football_api

services:
  db:
    image: mysql:8.1.0
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      <<: *env
    ports:
      - "3308:3306"
    networks:
      - api-football-network

  football-app:
    build: .
    networks:
      - api-football-network
    environment:
      <<: *env
      API_KEY: ${API_KEY}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    volumes:
      - ./artifact/files:/opt/artifact/files

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 60s -i 500ms
    networks:
      - api-football-network

networks:
  api-football-network:
    driver: bridge
